### ISSUE TITLE
Installation and first steps

### ISSUE THREAD

**Issue by k00ni** [lifr-reasoner/lifr#2]
I would like to test this reasoner, but found no installation guide. I assume I have to include your Java code into my project to be able to use the LiFR reasoner?

Also a short usage example would be very helpful.

**Comment by dorotheatsatsou** [comment]
Hi Konrad,

I can export a library (.jar file) if you would like. I'll try to also
provide a usage example.

The usage example may take a few days.

Best,
Dorothea

**Comment by k00ni** [comment]
Hello @dorotheatsatsou, thank you for your quick answer! A ready-to-use jar-file would be very helpful for new users like me. I assume there is a Java API or does LiFR also provides a CLI to interact with it?

_Small disclaimer:_ I am conducting a literature/software review on still usable OWL reasoners in 2023. This one is one of the few which seem to still be usable.

**Comment by dorotheatsatsou** [comment]
Yep, I know. You survey will be very useful to me as well since it's hard
to find other active reasoners for comperison, so I'd appreciate it if you
let me know when your survey is public.

Just a Java API, no CLI. I see I haven't published the documentation,
that's odd. I'll see to it as well.

I'll ping you when I have it updated. Are you very pressed with time?

**Comment by k00ni** [comment]
That is interesting to hear and I am glad you taking the time. Finding OWL reasoners which are still maintained is a hard task, for sure. Its an important part of the Semantic Web software stack but seem to be forgotten.

> I'll ping you when I have it updated. Are you very pressed with time?

No, take your time (I plan to submit in a month or two). I have most of the information I need for now. In my study my focus is summarizing information about a reasoner, add some references and links and, if available, provide short info how to install and use it.

**Comment by k00ni** [comment]
I am almost finished with my study and checking a few remaining items. Could you find the time yet? Can you also tell me if this reasoner is still actively maintained? Thanks.

**Comment by dorotheatsatsou** [comment]
Heya. I didn't have time to do much, especially in terms of documentation, but I have created and tested a few examples for all the main reasoning services and provided usage details in the main page/readme file. 

I hope that the simplicity and naming conventions of the examples are intuitive enough so that everyone will able to use the reasoner. 

I've also exported the project as a jar file (not executable) to enable importing it as a library in other Java projects. 

Yes, it is actively maintained although pushes might be delayed, but anyone that contacts me here can request speeding up updates/releases. 

There are two major core algorithm additions made, which I describe in the (new) planned upcoming features section. They will be merged with this project at some point - hopefully sooner than later.

**Comment by dorotheatsatsou** [comment]
Examples are now fully commented and a real-world use case example has been added. I hope this adequately covers first steps, so I will be closing this issue.

**Comment by k00ni** [comment]
Thank you very much.

**Comment by k00ni** [comment]
@dorotheatsatsou I published the results of my research on arxiv.org: https://arxiv.org/abs/2309.06888

**Comment by dorotheatsatsou** [comment]
Thank you very much for the update Konrad. And the work done, very helpful.
